version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"  # change {local port}:8081 if it is being used
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/test?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"  # change {local port}:3306 if it is being used
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"  # change {local port}:6379 if it is being used
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
