spring.application.name=demo
#spring.config.import=configserver:


spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/test?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Monu@2178}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}


spring.datasource.tomcat.initial-size=5
spring.datasource.tomcat.max-wait=10000
spring.datasource.tomcat.max-active=50
spring.datasource.tomcat.max-idle=15
spring.datasource.tomcat.min-idle=8
spring.datasource.tomcat.validation-query=SELECT 1
spring.datasource.tomcat.test-on-borrow=true
spring.datasource.tomcat.test-while-idle=true

spring.cloud.config.enabled=false
# Google OAuth2 client configuration
spring.security.oauth2.client.registration.google.client-id=990348001980-g8m4abf4cfu4m46tsds19fe0uj1n8re9.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub
#
jwt.secret=jR4zK2qP8xW7nM9vL3hT6cD1bY5gF0sE
server.port=8081
