spring.application.name=demo
#spring.config.import=configserver:


spring.datasource.url=jdbc:mysql://localhost:3306/test2?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Eeshi@2707
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Redis config
spring.redis.host=localhost
spring.redis.port=6379
spring.cache.type=redis


spring.cloud.config.enabled=false
# Google OAuth2 client configuration
spring.security.oauth2.client.registration.google.client-id=990348001980-g8m4abf4cfu4m46tsds19fe0uj1n8re9.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub
#
jwt.secret=jR4zK2qP8xW7nM9vL3hT6cD1bY5gF0sE
# Server port
server.port=8080
